package spring

import (
	"bytes"
	"errors"
	"fmt"
	"slices"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/whoisclebs/heimdall-lint/internal/schema"
)

type Options struct {
	// Prefixes restricts the import to properties starting with one of them
	// (for example "api."). Empty means every property.
	Prefixes []string
}

// EnvironmentName converts a property name to the environment variable Spring
// Boot binds it to: dots become underscores, dashes are removed, upper case.
// Indexed and wildcard properties have no single variable and return false.
func EnvironmentName(property string) (string, bool) {
	if strings.ContainsAny(property, "[]*") {
		return "", false
	}
	name := strings.ToUpper(strings.NewReplacer(".", "_", "-", "").Replace(property))
	return name, name != ""
}

type outVariable struct {
	Type        string   `yaml:"type"`
	Description string   `yaml:"description,omitempty"`
	Default     any      `yaml:"default,omitempty"`
	Min         *int     `yaml:"min,omitempty"`
	Max         *int     `yaml:"max,omitempty"`
	Values      []string `yaml:"values,omitempty"`
	Deprecated  bool     `yaml:"deprecated,omitempty"`
	Replacement string   `yaml:"replacement,omitempty"`
}

type outSchema struct {
	Version   int                    `yaml:"version"`
	Variables map[string]outVariable `yaml:"variables"`
}

const header = `# Generated by "heimdall schema generate" from Spring Boot configuration metadata.
# Spring does not say which properties are mandatory: review the result and set
# "required: true" where your application needs a value.
`

// Generate builds a schema from metadata. Warnings describe anything skipped
// or adjusted; the returned YAML is always a schema Heimdall itself accepts.
func Generate(metadata *Metadata, options Options) ([]byte, []string, error) {
	variables, warnings := build(metadata, options)
	if len(variables) == 0 {
		return nil, warnings, errors.New("no properties to import (check --prefix)")
	}

	document, err := render(variables)
	if err != nil {
		return nil, warnings, err
	}
	// Anything the schema rules reject (typically an incompatible default) is
	// repaired by dropping that default, never by emitting an invalid schema.
	if dropped := invalidDefaults(document); len(dropped) > 0 {
		for _, name := range dropped {
			variable := variables[name]
			warnings = append(warnings, fmt.Sprintf("%s: dropped default %v, which is not valid for type %s", name, variable.Default, variable.Type))
			variable.Default = nil
			variables[name] = variable
		}
		if document, err = render(variables); err != nil {
			return nil, warnings, err
		}
	}
	if _, err := schema.Parse(document, "generated"); err != nil {
		return nil, warnings, fmt.Errorf("generated schema is invalid: %w", err)
	}
	return document, warnings, nil
}

func build(metadata *Metadata, options Options) (map[string]outVariable, []string) {
	hints := enumHints(metadata.Hints)
	properties := slices.Clone(metadata.Properties)
	slices.SortFunc(properties, func(a, b Property) int { return strings.Compare(a.Name, b.Name) })

	variables := map[string]outVariable{}
	owner := map[string]string{}
	var warnings []string
	for _, property := range properties {
		if !selected(property.Name, options.Prefixes) {
			continue
		}
		name, ok := EnvironmentName(property.Name)
		if !ok {
			warnings = append(warnings, fmt.Sprintf("skipped %s: indexed or wildcard properties have no single environment variable", property.Name))
			continue
		}
		if other, taken := owner[name]; taken {
			warnings = append(warnings, fmt.Sprintf("skipped %s: maps to %s, already used by %s", property.Name, name, other))
			continue
		}
		owner[name] = property.Name
		variables[name] = convert(property, hints[property.Name])
	}

	// A replacement is only kept when the replacing variable was imported too.
	for name, variable := range variables {
		if variable.Replacement == "" {
			continue
		}
		if _, declared := variables[variable.Replacement]; !declared {
			variable.Replacement = ""
			variables[name] = variable
		}
	}
	return variables, warnings
}

func selected(name string, prefixes []string) bool {
	if len(prefixes) == 0 {
		return true
	}
	return slices.ContainsFunc(prefixes, func(prefix string) bool { return strings.HasPrefix(name, prefix) })
}

func enumHints(hints []Hint) map[string][]string {
	byName := map[string][]string{}
	for _, hint := range hints {
		var values []string
		for _, value := range hint.Values {
			if text, ok := value.Value.(string); ok && text != "" && !slices.Contains(values, text) {
				values = append(values, text)
			}
		}
		if len(values) > 0 {
			byName[hint.Name] = values
		}
	}
	return byName
}

func convert(property Property, enumValues []string) outVariable {
	variable := outVariable{
		Type:        schemaType(property.Type),
		Description: strings.TrimSpace(property.Description),
		Default:     scalarDefault(property.DefaultValue),
	}
	if len(enumValues) > 0 && variable.Type == "string" {
		variable.Type, variable.Values = "enum", enumValues
	}
	if variable.Type == "integer" && strings.HasSuffix(property.Name, ".port") {
		low, high := 0, 65535 // Spring allows port 0 (random port)
		variable.Min, variable.Max = &low, &high
	}
	if property.Deprecation != nil {
		variable.Deprecated = true
		if replacement, ok := EnvironmentName(property.Deprecation.Replacement); ok && property.Deprecation.Replacement != "" {
			variable.Replacement = replacement
		}
	}
	return variable
}

// schemaType maps a Java type to a Heimdall type. Anything not clearly numeric,
// boolean, temporal or a URL is a string: collections, maps and custom
// objects are bound from comma-separated or structured text.
func schemaType(javaType string) string {
	base, _, _ := strings.Cut(javaType, "<")
	switch base {
	case "int", "long", "short", "byte", "java.lang.Integer", "java.lang.Long", "java.lang.Short", "java.lang.Byte", "java.math.BigInteger":
		return "integer"
	case "float", "double", "java.lang.Float", "java.lang.Double", "java.math.BigDecimal":
		return "float"
	case "boolean", "java.lang.Boolean":
		return "boolean"
	case "java.time.Duration":
		return "duration"
	case "java.net.URL", "java.net.URI":
		return "url"
	}
	return "string"
}

func scalarDefault(value any) any {
	switch typed := value.(type) {
	case bool, string:
		return typed
	case float64:
		if typed == float64(int64(typed)) {
			return int64(typed)
		}
		return typed
	}
	return nil // absent, null, arrays and objects have no scalar default
}

func render(variables map[string]outVariable) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(header)
	encoder := yaml.NewEncoder(&out)
	encoder.SetIndent(2)
	if err := encoder.Encode(outSchema{Version: schema.SupportedVersion, Variables: variables}); err != nil {
		return nil, err
	}
	return out.Bytes(), encoder.Close()
}

// invalidDefaults returns variables whose only schema problem is their default.
func invalidDefaults(document []byte) []string {
	_, err := schema.Parse(document, "generated")
	var invalid *schema.Error
	if !errors.As(err, &invalid) {
		return nil
	}
	var names []string
	for _, problem := range invalid.Problems {
		if problem.Variable != "" && strings.HasPrefix(problem.Message, "default value is invalid") && !slices.Contains(names, problem.Variable) {
			names = append(names, problem.Variable)
		}
	}
	return names
}
